namespace PaintDotNet.Direct2D
{
    using PaintDotNet;
    using PaintDotNet.ComponentModel;
    using PaintDotNet.DirectWrite;
    using PaintDotNet.Imaging;
    using PaintDotNet.Interop;
    using PaintDotNet.Rendering;
    using System;
    using System.Runtime.InteropServices;

    [PrecacheAutoGeneratedProxyFactory, NativeInterfaceID("06152247-6f50-465a-9245-118bfd3b6007")]
    public interface IDirect2DFactory : IDirect2DObject, IObjectRef, IDisposable, IIsDisposed, IGeometryFactory
    {
        IRenderTarget CreateBitmapRenderTarget(IBitmap target, RenderTargetProperties renderTargetProps);
        IDCRenderTarget CreateDCRenderTarget(RenderTargetProperties renderTargetProps);
        IDrawingStateBlock CreateDrawingStateBlock(DrawingStateDescription? drawingStateDescription = new DrawingStateDescription?(), ITextRenderingParams textRenderingParams = null);
        IHwndRenderTarget CreateHwndRenderTarget(RenderTargetProperties renderTargetProperties, HwndRenderTargetProperties hwndRenderTargetProperties);
        void ReloadSystemMetrics();

        VectorFloat DesktopDpi { get; }
    }
}

