namespace PaintDotNet.Imaging
{
    using PaintDotNet;
    using PaintDotNet.ComponentModel;
    using PaintDotNet.Interop;
    using PaintDotNet.Rendering;
    using System;

    [CustomImplementationAllowed, PrecacheAutoGeneratedProxyFactory, NativeInterfaceID("00000121-a8f2-4877-ba0a-fd2b6645fb94")]
    public interface IBitmap : IBitmapSource, IImagingObject, IObjectRef, IDisposable, IIsDisposed
    {
        IBitmapLock Lock(RectInt32 rect, BitmapLockOptions lockOptions);

        IPalette Palette { get; set; }

        VectorDouble Resolution { get; set; }
    }
}

