namespace PaintDotNet.Imaging
{
    using PaintDotNet;
    using PaintDotNet.ComponentModel;
    using System;

    [PrecacheAutoGeneratedGenericProxyFactory(typeof(ColorAlpha8)), PrecacheAutoGeneratedGenericProxyFactory(typeof(ColorBgra32)), PrecacheAutoGeneratedGenericProxyFactory(typeof(ColorPbgra32))]
    public interface IBitmapLock<TPixel> : IBitmapLock, IImagingObject, IObjectRef, IDisposable, IIsDisposed, IBitmapLockData, IBitmapLockData<TPixel> where TPixel: struct, INaturalPixelInfo
    {
    }
}

