namespace PaintDotNet.Imaging
{
    using PaintDotNet;
    using PaintDotNet.ComponentModel;
    using PaintDotNet.Rendering;
    using System;

    [PrecacheAutoGeneratedGenericProxyFactory(typeof(ColorAlpha8)), PrecacheAutoGeneratedGenericProxyFactory(typeof(ColorBgra32)), PrecacheAutoGeneratedGenericProxyFactory(typeof(ColorPbgra32))]
    public interface IBitmap<TPixel> : IBitmap, IBitmapSource, IImagingObject, IObjectRef, IDisposable, IIsDisposed, IBitmapSource<TPixel> where TPixel: struct, INaturalPixelInfo
    {
        IBitmapLock<TPixel> Lock(RectInt32 rect, BitmapLockOptions lockOptions);
    }
}

