namespace PaintDotNet.Imaging
{
    using PaintDotNet;
    using PaintDotNet.ComponentModel;
    using PaintDotNet.Interop;
    using System;

    [PrecacheAutoGeneratedProxyFactory, CustomImplementationAllowed, NativeInterfaceID("00000123-a8f2-4877-ba0a-fd2b6645fb94")]
    public interface IBitmapLock : IImagingObject, IObjectRef, IDisposable, IIsDisposed, IBitmapLockData
    {
    }
}

