namespace PaintDotNet.Imaging
{
    using PaintDotNet;
    using PaintDotNet.ComponentModel;
    using System;

    [PrecacheAutoGeneratedGenericProxyFactory(typeof(ColorAlpha8)), PrecacheAutoGeneratedGenericProxyFactory(typeof(ColorBgra32)), PrecacheAutoGeneratedGenericProxyFactory(typeof(ColorPbgra32))]
    public interface IBitmapSource<TPixel> : IBitmapSource, IImagingObject, IObjectRef, IDisposable, IIsDisposed where TPixel: struct, INaturalPixelInfo
    {
    }
}

